# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/gpio_defs.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/irq_ctrl_defs.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_defs.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/spi_lite_defs.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/timer_defs.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/uart_lite_defs.v}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/gpio_defs.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/irq_ctrl_defs.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_defs.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/spi_lite_defs.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/timer_defs.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/uart_lite_defs.v}}]
read_verilog -library xil_defaultlib {
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/fpga/arty/artix7_pll.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/axi4_arb.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/fpga/arty/axi4_cdc.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/axi4_lite_tap.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/axi4_retime.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/axi4lite_axi4_conv.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/Downloads/boolean_bram.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/fpga/arty/dbg_bridge.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/fpga/arty/dbg_bridge_fifo.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/fpga/arty/dbg_bridge_uart.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/dport_bridge.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/fpga/arty/fpga_top.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/gpio.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/icache.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/icache_data_ram.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/icache_tag_ram.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/irq_ctrl.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_alu.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_core.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_csr.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_decode.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_exec.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_fetch.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_lsu.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_mmu.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_mmu_arb.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_muldiv.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/core/core/rv32imsu/riscv_regfile.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/riscv_soc.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/riscv_top.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/soc.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/spi_lite.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/timer.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/riscv_soc - Copy/soc/uart_lite.v}
  {C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/sources_1/imports/Downloads/boolean_top.v}
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/constrs_1/new/Constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Administrator/Desktop/SSIR/riscv_soc - Copy/fpga/arty/project.srcs/constrs_1/new/Constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
